# This file was generated by GoReleaser. DO NOT EDIT.
cask "taw-fleet" do
  version "1.7.0"

  on_macos do
    on_arm do
      sha256 "65c335d291a7a310dca3ece95b1b9bd519f33464ac72f22027b5750d5a48da6d"
      url "https://github.com/Relmaur/taw-fleet/releases/download/v#{version}/taw-fleet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "81f9b789be1ee03c74f62c5956a606c188957abd42b0bdd759b794fb54392018"
      url "https://github.com/Relmaur/taw-fleet/releases/download/v#{version}/taw-fleet_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "taw-fleet"
  desc "The TAW sites on this Mac (Local by Flywheel) in one terminal dashboard"
  homepage "https://github.com/Relmaur/taw-fleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taw-fleet"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taw-fleet"]
    end
  end

  # No zap stanza required
end
