# This file was generated by GoReleaser. DO NOT EDIT.
cask "taw-fleet" do
  version "1.3.1"

  on_macos do
    on_arm do
      sha256 "930f77601c9e5acbd52f4bfa777604e16ee8b114f6a87fcf8c357d5c9e4a5e10"
      url "https://github.com/Relmaur/taw-fleet/releases/download/v#{version}/taw-fleet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d9dfa77bf6323d13c0172bae658182c02c68353b37aee171efc86fdcdc0eba38"
      url "https://github.com/Relmaur/taw-fleet/releases/download/v#{version}/taw-fleet_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "taw-fleet"
  desc "The TAW sites on this Mac (Local by Flywheel) in one terminal dashboard"
  homepage "https://github.com/Relmaur/taw-fleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taw-fleet"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taw-fleet"]
    end
  end

  # No zap stanza required
end
