# This file was generated by GoReleaser. DO NOT EDIT.
cask "taw-fleet" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "3fa7e825cecdab8a0679cb4254e64bf57bb724e3b517f043ea07aed9a7de7404"
      url "https://github.com/Relmaur/taw-fleet/releases/download/v#{version}/taw-fleet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "70280d11bf77facefbbe764fbda8c17d1384d3d2f5760c60659e9d03b133fa91"
      url "https://github.com/Relmaur/taw-fleet/releases/download/v#{version}/taw-fleet_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "taw-fleet"
  desc "The TAW sites on this Mac (Local by Flywheel) in one terminal dashboard"
  homepage "https://github.com/Relmaur/taw-fleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taw-fleet"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taw-fleet"]
    end
  end

  # No zap stanza required
end
